version: '3.8'

services:
  books-db:
    image: mysql:8.0.37
    container_name: peeppea.books-db
    environment:
      MYSQL_ROOT_PASSWORD: Devindrew42!
      MYSQL_DATABASE: peeppea_booksDB
      MYSQL_USER: drew
      MYSQL_PASSWORD: peeppea33
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  books-app:
    image: peeppea.books-image
    container_name: peeppea.books-container
    depends_on:
      - books-db
    environment:
      DB_HOST: peeppea.books-db
      DB_NAME: peeppea_booksDB
      DB_USERNAME: drew
      DB_PASSWORD: peeppea33
    ports:
      - "8080:8080"

volumes:
  db_data: