version: '3.8'

services:
  database:
    image: mysql:8.0.37
    container_name: peeppea.books-db
    environment:
      MYSQL_ROOT_PASSWORD: Devindrew42!
      MYSQL_DATABASE: peepea_booksDB
      MYSQL_USER: drew
      MYSQL_PASSWORD: peeppea33
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    image: peeppea.books-image
    container_name: peeppea.books-container
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/peepea_booksDB
      SPRING_DATASOURCE_USERNAME: drew
      SPRING_DATASOURCE_PASSWORD: peeppea33
    ports:
      - "8080:8080"

volumes:
  db_data:
